OldBoy_crm/OldBoy_crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
from crm import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^crm/', include("crm.urls")),
    url(r'^rbac/', include('rbac.urls')),
]

OldBoy_crm/crm/urls.py
from django.conf.urls import url
from . import views
from crm.viewplugs import auth, teacher, consultant

urlpatterns = [
    # # 用户相关,登陆,登出,注册
    url(r'^login/', auth.login, name="login"),
    url(r'^reg/', auth.reg, name="reg"),
    url(r'^logout/', auth.logout, name="logout"),
    url(r'^user_profile/', auth.user_profile, name="user_profile"),

    # 首页
    url(r'^index/', views.index, name="index"),
    #### 面向销售功能
    # 私户公户的展示
    url(r'^customer_list/', consultant.Customer_list.as_view(), name="customer_list"),
    url(r'^my_customer/', consultant.Customer_list.as_view(), name="my_customer"),

    # 客户更改>添加和更新客户
    url(r'^add_customer/', consultant.customer_change, name="add_customer"),
    url(r'^edit_customer/(\d+)/', consultant.customer_change, name="edit_customer"),

    # 跟进记录展示
    url(r'^consult_list/$', consultant.Consult_list.as_view(), name="consult_list"),  # 参看该销售的客户的跟进记录
    url(r'^consult_list/(?P<customer_id>\d+)/', consultant.Consult_list.as_view(), name="one_consult_list"),
    # 查看具体某一客户的跟进记录

    # 编辑跟进记录
    url(r'^add_consult/(?P<customer_id>\d+)/', consultant.consult_change, name="add_consult"),
    url(r'^edit_consult/(?P<pk>\d+)/$', consultant.consult_change, name="edit_consult"),  # 具体编辑某一条跟进记录

    # 展示报名记录
    # 展示一个销售填写报名记录
    url(r'^enrollment_list/$', consultant.EnrollmentList.as_view(), name='enrollment_list'),
    # 展示一个客户报名记录
    url(r'^enrollment_list/(?P<customer_id>\d+)/$', consultant.EnrollmentList.as_view(), name='one_enrollment_list'),

    # 添加报名表
    url(r'^add_enrollment/(?P<customer_id>\d+)/$', consultant.enrollment_change, name='add_enrollment'),
    # 编辑报名表
    url(r'^edit_enrollment/(\d+)/$', consultant.enrollment_change, name='edit_enrollment'),

    # 展示缴费记录
    # 展示一个销售的所有客户的缴费记录
    url(r'^payment_list/$', consultant.PaymentRecordList.as_view(), name='payment_list'),
    # 展示一个客户缴费记录
    url(r'^payment_list/(?P<customer_id>\d+)/$', consultant.PaymentRecordList.as_view(), name='one_payment_list'),

    # 添加缴费记录
    url(r'^add_payment/(?P<customer_id>\d+)/$', consultant.payment_change, name='add_payment'),
    # 编辑缴费记录
    url(r'^edit_payment/(\d+)/$', consultant.payment_change, name='edit_payment'),

    ###### 班级方面的功能

    # 展示班级列表
    url(r'^class_list/$', teacher.Classlist.as_view(), name='class_list'),

    # 添加班级
    url(r'^add_class/$', teacher.class_change, name='add_class'),
    # 编辑班级
    url(r'^edit_class/(\d+)/$', teacher.class_change, name='edit_class'),

    # 课程记录表
    # 展示班级的课程记录表
    url(r'^course_list/(?P<class_id>\d+)/$', teacher.Course_list.as_view(), name='course_list'),

    # 添加课程记录表
    url(r'^add_course_record/(?P<class_id>\d+)/$', teacher.course_record_change, name='add_course_record'),
    # 编辑课程记录表
    url(r'^edit_course_record/(?P<pk>\d+)/$', teacher.course_record_change, name='edit_course_record'),


    # 展示的学习记录
    url(r'^display_study_record/(?P<course_record_id>\d+)/$', teacher.study_record_list, name='display_study_record'),

]

OldBoy_crm/crm/models.py
from django.db import models
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe

course_choices = (('Linux', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),
                  ('LinuxMaintenance', 'Linux运维基础'),
                  ('GoFullStack', 'Go语言全栈开发'),
                  ('Html前端', 'Html前端'),
                  ('Javascript语言', 'Javascript语言编程'),
                  )

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class Department(models.Model):
    """
    部门表
    """
    name = models.CharField(max_length=32, verbose_name="部门名称")
    count = models.IntegerField(verbose_name="人数", default=0)

    def __str__(self):
        return self.name

    class Meta:
        # admin中显示的表名称
        verbose_name = '部门表'
        # verbose_name加s
        verbose_name_plural = '所有部门信息'
        # 数据库中生成的表名称 默认 app名称 + 下划线 + 类名
        # db_table = "table_name"

        # 联合索引
        # index_together = [("pub_date", "deadline"), ]  # 应为两个存在的字段

        ## 联合唯一索引
        # unique_together = (("driver", "restaurant"),)  # 应为两个存在的字段


from rbac.models import User


class UserProfile(User):
    """
    用户表
    """
    username = models.EmailField('登陆用户名', max_length=255, unique=True, )
    password = models.CharField('密码', max_length=128)
    name = models.CharField('真实名称', max_length=32)
    department = models.ForeignKey('Department', verbose_name='部门', default=None, blank=True, null=True)
    mobile = models.CharField('手机', max_length=32, default=None, blank=True, null=True)
    memo = models.TextField('备注', blank=True, null=True, default=None)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        # admin中显示的表名称
        verbose_name = '用户表'
        # verbose_name加s
        verbose_name_plural = '所有用户'


class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True)
    course = MultiSelectField("咨询课程", choices=course_choices)
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    consultant = models.ForeignKey('UserProfile', verbose_name="销售", related_name='customers', blank=True, null=True, )
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", blank=True, null=True)

    def __str__(self):
        return self.name

    def show_status(self):
        status_dic = {'已报名': "green",
                      '未报名': 'red',
                      '学习中': 'yellow',
                      '学费已交齐': 'gold'
                      }
        return mark_safe('<span style="color: white;background-color: {}">{}</span>'.format(
            status_dic.get(self.get_status_display()), self.get_status_display()))

    def show_class(self):
        return "、".join([str(i) for i in self.class_list.all()])

    class Meta:
        # admin中显示的表名称
        verbose_name = '客户表'
        # verbose_name加s
        verbose_name_plural = '所有客户'


class Campus(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        # admin中显示的表名称
        verbose_name = '校区表'
        # verbose_name加s


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campus', verbose_name="校区")
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)

    teachers = models.ManyToManyField('UserProfile', verbose_name="老师")

    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
                                  null=True)

    class Meta:
        # admin中显示的表名称
        verbose_name = '班级表'
        # verbose_name加s
        verbose_name_plural = '所有班级表'
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return "%s-%s期" % (self.get_course_display(), self.semester)

    def show_teachers(self):
        return '、'.join([str(i) for i in self.teachers.all()])


class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户", related_name='consult_records')
    note = models.TextField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserProfile", verbose_name="跟进人", related_name='records')
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    def __str__(self):
        text = '{}{}的跟进记录'.format(self.customer.name, self.date)
        return text

    class Meta:
        # admin中显示的表名称
        verbose_name = '跟进记录表'
        # verbose_name加s


class Enrollment(models.Model):
    """
    报名表
    """

    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
    contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称')
    school = models.ForeignKey('Campus')
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")

    class Meta:
        unique_together = ('enrolment_class', 'customer')

        # admin中显示的表名称
        verbose_name = '报名记录表'
        # verbose_name加s


class PaymentRecord(models.Model):
    """
    缴费记录表
    """
    pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
    paid_fee = models.IntegerField("费用数额", default=0)
    note = models.TextField("备注", blank=True, null=True)
    date = models.DateTimeField("交款日期", auto_now_add=True)
    course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
    class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
                                  default='N/A')
    enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True)
    customer = models.ForeignKey('Customer', verbose_name="客户")
    consultant = models.ForeignKey('UserProfile', verbose_name="销售")
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    status_choices = (
        (1, '未审核'),
        (2, '已审核'),
    )
    status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

    confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)

OldBoy_crm/crm/templates/consultant/consult_list.html
{% extends 'layout.html' %}

{% block content %}
    {% load my_tags %}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">跟进记录列表</h3>
        </div>
        <div class="panel-body">

            <div>
                {% if request.path_info == '/crm/consult_list/' %}
                    <a href="{% url 'add_consult' 0 %}" class="btn btn-primary">新增</a>
                {% else %}
                    <a href="{% url 'add_consult' customer_id %}" class="btn btn-primary">新增</a>
                {% endif %}


            </div>

            <form action="" class="form-inline pull-right">
                <input type="text" name="query" class="form-control">
                <button class="btn btn-sm btn-success">搜索</button>
            </form>

            <table class="table-hover table table-bordered table-responsive">
                <thead>
                <tr>
                    <th>序号</th>
                    <th>客户QQ号</th>
                    <th>客户名称</th>
                    <th>跟进内容</th>
                    <th>跟进状态</th>
                    <th>跟进时间</th>
                    <th>跟进人</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in consult_record %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ obj.customer.qq }}</td>
                        <td>{{ obj.customer.name }}</td>
                        <td>{{ obj.note|truncatechars:25 }}</td>
                        <td>{{ obj.get_status_display }}</td>
                        <td>{{ obj.date }}</td>
                        <td>{{ obj.consultant }}</td>
                        <td>
                            <a href="{% url 'edit_consult' obj.pk %}"
                               class="btn btn-primary btn-sm">编辑</a>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    {#    <div class="row">#}
    {#        <nav class="col-lg-8 col-lg-offset-4" aria-label="Page navigation">#}
    {#            <ul class="pagination">#}
    {#                {{ pagination.page_html|safe }}#}
    {#            </ul>#}
    {#        </nav>#}
    {#    </div>#}
{% endblock %}

OldBoy_crm/crm/templates/consultant/customer_list.html
{% extends "layout.html" %}

{% block css %}
    <style>
        #Inverse_selection {
            margin: -2px 0 0;
        }
    </style>
{% endblock %}

{% block content %}
    {% load my_tags %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">客户列表
            </h3>
        </div>
        <div class="panel-body">
            <div>
                <a class="btn btn-info" href="{% url 'add_customer' %}">添加客户</a>
            </div>
            <form action="" class="form-inline pull-right">
                <input type="text" class="form-control" name="query">
                <sapn><input type="submit" class="btn btn-sm btn-success" value="搜索"></sapn>
            </form>
            <form action="" method="post" class="form-inline">
                {% csrf_token %}

                <select name="action" id="" class="form-control">
                    {% if request.path == '/crm/customer_list/' %}
                        <option value="pub_convert_pri" selected>公户转私户</option>
                    {% else %}
                        <option value="pri_convert_pub" selected>私户转公户</option>
                    {% endif %}
                    <option value="mult_del">批量删除</option>
                </select>
                <button type="submit" class="btn btn-info">转换客户</button>
                <table class="table table-striped table-hover table-bordered table-responsive">
                    <thead>
                    <tr>
                        <th>
                            <span class="btn btn-xs btn-success" class='form-group' id="Inverse_selection">反选

                    </span>
                        </th>
                        <th class="text-center">序号</th>
                        <th class="text-center">ID</th>
                        <th class="text-center">qq</th>
                        <th class="text-center">姓名</th>
                        <th class="text-center">性别</th>
                        <th class="text-center">手机号</th>
                        <th class="text-center">客户来源</th>
                        <th class="text-center">咨询课程</th>
                        <th class="text-center">班级类型</th>
                        <th class="text-center">状态</th>
                        <th class="text-center">下次跟进时间</th>
                        <th class="text-center">销售</th>
                        <th class="text-center">已报班级</th>
                        {% if request.path_info != '/crm/customer_list/' %}
                            <th class="text-center">操作</th>
                        {% endif %}

                    </tr>
                    </thead>
                    <tbody>
                    {% for customer in customer_list %}
                        <tr>
                            <td class="text-center">
                                <input type="checkbox" value="{{ customer.pk }}" name="customer">
                            </td>
                            <td class="text-center">{{ forloop.counter }}</td>
                            <td class="text-center">{{ customer.pk }}</td>
                            <td class="text-center">{{ customer.qq }}</td>
                            <td class="text-center">{{ customer.name|default:'无' }}</td>
                            <td class="text-center">{{ customer.get_sex_display }}</td>
                            <td class="text-center">{{ customer.phone|default:'无' }}</td>
                            <td class="text-center">{{ customer.get_source_display }}</td>
                            <td class="text-center">{{ customer.course }}</td>
                            <td class="text-center">{{ customer.get_class_type_display }}</td>
                            <td class="text-center">{{ customer.show_status }}</td>
                            <td class="text-center">{{ customer.next_date|default:'无' }}</td>
                            <td class="text-center">{{ customer.consultant.name }}</td>
                            <td>
                                {{ customer.show_class }}
                            </td>
                            {% if request.path_info != '/crm/customer_list/' %}
                                <td>
                                    <a class="btn btn-warning btn-xs"
                                       href="{% reverse_url request 'edit_customer' customer.pk %}">编辑</a>
                                    <a class="btn btn-warning btn-xs"
                                       href="{% reverse_url request 'one_consult_list' customer.pk %}">查看跟进</a>
                                    <a href="{% reverse_url request 'one_enrollment_list' customer.pk %}"
                                       class="btn btn-primary btn-xs">查看报名表</a>
                                    <a href="{% url  'add_enrollment' customer.pk %}"
                                       class="btn btn-primary btn-xs">添加报名表</a>
                                </td>
                            {% endif %}

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </form>
            <div class="row">
                <nav class="col-lg-8 col-lg-offset-4" aria-label="Page navigation">
                    <ul class="pagination">
                        {{ obj.page_html|safe }}
                    </ul>
                </nav>
            </div>


            <div>
                <form action="" method="post" class="form-inline">
                    {% csrf_token %}
                    <input class="form-control" type="text" name='page' placeholder="请输入跳转的页面">
                    <button type='submit' class="btn btn-sm btn-primary">跳转页面</button>

                </form>
            </div>

        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $('#Inverse_selection').click(function () {
            for (i = 0; i < $('[name=customer]').length; i++) {
                if ($('[name="customer"]')[i].checked == false) {
                    $('[name="customer"]')[i].checked = true
                } else {
                    $('[name="customer"]')[i].checked = false
                }
            }
        })
    </script>
{% endblock %}

OldBoy_crm/crm/templates/consultant/enrollment_list.html
{% extends 'layout.html' %}

{% block content %}

    <div class="panel panel-default">

        <div class="panel-heading">
            <h3 class="panel-title">报名记录列表</h3>
        </div>


        <div class="panel-body">
            <div>
                {% if request.path_info == '/crm/enrollment_list/' %}
                    <a href="{% url 'add_enrollment' 0 %}" class="btn btn-primary">新增</a>
                {% else %}
                    <a href="{% url 'add_enrollment' customer_id %}" class="btn btn-primary">新增</a>
                {% endif %}
            </div>
            <form action="" class="form-inline pull-right">
                <input type="text" class="form-control" name="query">
                <button class="btn btn-sm btn-success">搜索</button>
            </form>
            {#            <div><a class="btn btn-sm btn-info" href="{% url 'add_enrollment' 0 %}">新增</a></div>#}


            <table class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>序号</th>
                    <th>客户</th>
                    <th>报名班级</th>
                    <th>校区</th>
                    <th>审核状态</th>
                    <th>报名日期</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for enrollment in all_enrollment %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ enrollment.customer }}</td>
                        <td>{{ enrollment.enrolment_class }}</td>
                        <td>{{ enrollment.school }}</td>
                        <td>{{ enrollment.contract_approved }}</td>
                        <td>{{ enrollment.enrolled_date }}</td>
                        <td>
                            <a href="{% url 'edit_enrollment' enrollment.pk %}" class="btn btn-primary btn-sm">编辑</a>
                        </td>
                    </tr>
                {% endfor %}


                </tbody>
            </table>


            {#    <div class="row">#}
            {#        <nav class="col-lg-8 col-lg-offset-4" aria-label="Page navigation">#}
            {#            <ul class="pagination">#}
            {#                {{ pagination.page_html|safe }}#}
            {#            </ul>#}
            {#        </nav>#}
            {#    </div>#}
        </div>
    </div>

{% endblock %}

OldBoy_crm/crm/templates/consultant/payment_list.html
{% extends 'layout.html' %}

{% block content %}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">缴费列表</h3>
        </div>
        <div class="panel-body">
            <div>
                <a class="btn btn-info" href="{% url 'add_payment' 0 %}">添加缴费记录</a>
            </div>
            <form action="" class="form-inline pull-right">
                <input type="text" class="form-control" name="query">
                <input type="submit" class="btn btn-sm btn-success" value="搜索">
            </form>


            <table class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>序号</th>
                    <th>客户</th>
                    <th>课程名</th>
                    <th>所报班级</th>
                    <th>费用类型</th>
                    <th>费用数额</th>
                    <th>交款日期</th>
                    <th>销售人</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for payment in all_payment %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ payment.customer }}</td>
                        <td>{{ payment.get_course_display }}</td>
                        <td>{{ payment.enrolment_class }}</td>
                        <td>{{ payment.get_pay_type_display }}</td>
                        <td>{{ payment.paid_fee }}</td>
                        <td>{{ payment.date }}</td>
                        <td>{{ payment.customer.consultant }}</td>
                        <td>
                            <a href="{% url 'edit_payment' payment.pk %}" class="btn btn-primary btn-sm">编辑</a>
                        </td>
                    </tr>
                {% endfor %}


                </tbody>
            </table>
            {#    <div class="row">#}
            {#        <nav class="col-lg-8 col-lg-offset-4" aria-label="Page navigation">#}
            {#            <ul class="pagination">#}
            {#                {{ pagination.page_html|safe }}#}
            {#            </ul>#}
            {#        </nav>#}
            {#    </div>#}
        </div>
    </div>
{% endblock %}